version: '2'
services:

  producer:
    image: 1602/alpine-node:4
    environment:
      - RABBIT_HOST=rabbit
    working_dir: /src
    volumes:
      - ./producer.js:/src/index.js
      - ../../:/src/node_modules/transport-rabbit
    command: [ 'node', 'index.js' ]

  consumer:
    image: 1602/alpine-node:4
    environment:
      - RABBIT_HOST=rabbit
    working_dir: /src
    volumes:
      - ./consumer.js:/src/index.js
      - ../../:/src/node_modules/transport-rabbit
    command: [ 'node', 'index.js' ]

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      - HOSTNAME=rabbit
      - RABBITMQ_NODENAME=rabbit
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    #volumes:
    #  - "/opt/rabbitmq/volume:/var/lib/rabbitmq"

